// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;

#nullable disable

namespace Server.Migrations.Tenant
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808203458_AddBreedingEventOffspring")]
    partial class AddBreedingEventOffspring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.AnimalProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalCount")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<string>("CollectedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRealization")
                        .HasColumnType("boolean");

                    b.Property<int?>("LivestockId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("LivestockId");

                    b.HasIndex("ProductionTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("AnimalProductions");
                });

            modelBuilder.Entity("Server.Models.BreedingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BreedingDate")
                        .HasColumnType("date");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FailedDate")
                        .HasColumnType("date");

                    b.Property<int?>("FemaleAnimalId")
                        .HasColumnType("integer");

                    b.Property<int?>("LivestockId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaleAnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("OffspringCount")
                        .HasColumnType("integer");

                    b.Property<int?>("OffspringLivestockId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PregnancyConfirmedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FemaleAnimalId");

                    b.HasIndex("LivestockId");

                    b.HasIndex("MaleAnimalId");

                    b.ToTable("BreedingEvents");
                });

            modelBuilder.Entity("Server.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Server.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "greenhouse",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "CropFarming",
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "livestock",
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "fruitstock",
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "marketplace",
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "calendar",
                            Value = 1
                        });
                });

            modelBuilder.Entity("Server.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Server.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<string>("Boundary")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("Server.Models.FruitKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FruitKinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Banana"
                        });
                });

            modelBuilder.Entity("Server.Models.Greenhouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("EstablishDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Greenhouses");
                });

            modelBuilder.Entity("Server.Models.GreenhouseFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("GreenhouseFloors");
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("EquipmentCost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("ExpectedHarvestDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("FuelCost")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WorkersCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("GreenhouseHarvests");
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestChemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GreenhouseHarvestId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseHarvestId");

                    b.ToTable("GreenhouseHarvestChemicals");
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseHarvestId")
                        .HasColumnType("integer");

                    b.Property<int>("GreenhouseStockId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseHarvestId");

                    b.HasIndex("GreenhouseStockId");

                    b.ToTable("GreenhouseHarvestItems");
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseHarvestId")
                        .HasColumnType("integer");

                    b.Property<int>("GreenhouseStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseHarvestId");

                    b.HasIndex("GreenhouseStockId");

                    b.ToTable("GreenhouseHarvestResults");
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseHarvestId")
                        .HasColumnType("integer");

                    b.Property<int>("GreenhouseSeedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseHarvestId");

                    b.HasIndex("GreenhouseSeedId");

                    b.ToTable("GreenhouseHarvestSeeds");
                });

            modelBuilder.Entity("Server.Models.GreenhouseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenhouseFloorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rotation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseFloorId");

                    b.ToTable("GreenhouseSections");
                });

            modelBuilder.Entity("Server.Models.GreenhouseSectionStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenhouseSectionId")
                        .HasColumnType("integer");

                    b.Property<int>("GreenhouseStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseSectionId");

                    b.HasIndex("GreenhouseStockId");

                    b.ToTable("GreenhouseSectionStocks");
                });

            modelBuilder.Entity("Server.Models.GreenhouseSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("GreenhouseSeeds");
                });

            modelBuilder.Entity("Server.Models.GreenhouseStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("GreenhouseStocks");
                });

            modelBuilder.Entity("Server.Models.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("EquipmentCost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("ExpectedHarvestDate")
                        .HasColumnType("date");

                    b.Property<int?>("FarmId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FuelCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LandPlotId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WorkersCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("LandPlotId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("Server.Models.HarvestChemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.ToTable("HarvestChemicals");
                });

            modelBuilder.Entity("Server.Models.HarvestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer");

                    b.Property<int?>("TreeStockId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.HasIndex("StockId");

                    b.HasIndex("TreeStockId");

                    b.ToTable("HarvestItems");
                });

            modelBuilder.Entity("Server.Models.HarvestProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<int>("TreeProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.HasIndex("TreeProductId");

                    b.ToTable("HarvestProducts");
                });

            modelBuilder.Entity("Server.Models.HarvestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer");

                    b.Property<int?>("TreeStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.HasIndex("StockId");

                    b.HasIndex("TreeStockId");

                    b.ToTable("HarvestResults");
                });

            modelBuilder.Entity("Server.Models.HarvestSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<int>("SeedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.HasIndex("SeedId");

                    b.ToTable("HarvestSeeds");
                });

            modelBuilder.Entity("Server.Models.HarvestTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HarvestedAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TreeStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.HasIndex("TreeStockId");

                    b.ToTable("HarvestTrees");
                });

            modelBuilder.Entity("Server.Models.LandPlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<string>("Crop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer");

                    b.Property<int?>("TreeStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("TreeStockId");

                    b.ToTable("LandPlots");
                });

            modelBuilder.Entity("Server.Models.Livestock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int?>("MeatProductionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("MeatProductionTypeId");

                    b.HasIndex("ProductionTypeId");

                    b.ToTable("Livestock");
                });

            modelBuilder.Entity("Server.Models.LivestockDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BornDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LivestockId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentOneId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentTwoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.HasIndex("ParentOneId");

                    b.HasIndex("ParentTwoId");

                    b.ToTable("LivestockDetails");
                });

            modelBuilder.Entity("Server.Models.LivestockKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LivestockKinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sheep"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pig"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Duck"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Goat"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rabbit"
                        });
                });

            modelBuilder.Entity("Server.Models.LivestockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<int>("LivestockId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.ToTable("LivestockMovements");
                });

            modelBuilder.Entity("Server.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinicName")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .HasColumnType("text");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("Medication")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<string>("Treatment")
                        .HasColumnType("text");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Server.Models.PlantScanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<bool>("PlantDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PreventionTips")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Treatments")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("PlantScanHistories");
                });

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Server.Models.ProductionMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<int?>("MarketListingId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductionMovements");
                });

            modelBuilder.Entity("Server.Models.ProductionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wool"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Honey"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Manure"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Silk"
                        });
                });

            modelBuilder.Entity("Server.Models.Seed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Seeds");
                });

            modelBuilder.Entity("Server.Models.SeedMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<int?>("HarvestSeedId")
                        .HasColumnType("integer");

                    b.Property<int>("SeedId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HarvestSeedId");

                    b.HasIndex("SeedId");

                    b.ToTable("SeedMovements");
                });

            modelBuilder.Entity("Server.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Server.Models.StockFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("LivestockId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.HasIndex("StockId");

                    b.ToTable("StockFeeds");
                });

            modelBuilder.Entity("Server.Models.StockHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockHistories");
                });

            modelBuilder.Entity("Server.Models.StockKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StockKinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Weat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beans"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cabbage"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eggplant"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pumpkin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tomato"
                        });
                });

            modelBuilder.Entity("Server.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<int?>("HarvestItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("HarvestResultId")
                        .HasColumnType("integer");

                    b.Property<int?>("MarketListingId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestItemId");

                    b.HasIndex("HarvestResultId");

                    b.HasIndex("StockId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Server.Models.StockPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TakenAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockPhotos");
                });

            modelBuilder.Entity("Server.Models.TreeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TreeProducts");
                });

            modelBuilder.Entity("Server.Models.TreeProductMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<int?>("HarvestProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TreeProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestProductId");

                    b.HasIndex("TreeProductId");

                    b.ToTable("TreeProductMovements");
                });

            modelBuilder.Entity("Server.Models.TreeStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("LandPlotId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TreeProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LandPlotId");

                    b.HasIndex("TreeProductId");

                    b.ToTable("TreeStocks");
                });

            modelBuilder.Entity("Server.Models.TreeStockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<int?>("HarvestItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("HarvestResultId")
                        .HasColumnType("integer");

                    b.Property<int?>("MarketListingId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TreeStockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HarvestItemId");

                    b.HasIndex("HarvestResultId");

                    b.HasIndex("TreeStockId");

                    b.ToTable("TreeStockMovements");
                });

            modelBuilder.Entity("Server.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kilogram",
                            ShortName = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Liter",
                            ShortName = "L"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Piece",
                            ShortName = "pcs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gram",
                            ShortName = "g"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dozen",
                            ShortName = "dz"
                        });
                });

            modelBuilder.Entity("Server.Models.AnimalProduction", b =>
                {
                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.Livestock", null)
                        .WithMany()
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.ProductionType", null)
                        .WithMany()
                        .HasForeignKey("ProductionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.BreedingEvent", b =>
                {
                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("FemaleAnimalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Models.Livestock", null)
                        .WithMany()
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("MaleAnimalId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Server.Models.GreenhouseFloor", b =>
                {
                    b.HasOne("Server.Models.Greenhouse", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvest", b =>
                {
                    b.HasOne("Server.Models.Greenhouse", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestChemical", b =>
                {
                    b.HasOne("Server.Models.GreenhouseHarvest", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseHarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestItem", b =>
                {
                    b.HasOne("Server.Models.GreenhouseHarvest", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseHarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.GreenhouseStock", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestResult", b =>
                {
                    b.HasOne("Server.Models.GreenhouseHarvest", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseHarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.GreenhouseStock", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseHarvestSeed", b =>
                {
                    b.HasOne("Server.Models.GreenhouseHarvest", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseHarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.GreenhouseSeed", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseSeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseSection", b =>
                {
                    b.HasOne("Server.Models.GreenhouseFloor", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseFloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseSectionStock", b =>
                {
                    b.HasOne("Server.Models.GreenhouseSection", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.GreenhouseStock", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseSeed", b =>
                {
                    b.HasOne("Server.Models.Greenhouse", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.GreenhouseStock", b =>
                {
                    b.HasOne("Server.Models.Greenhouse", null)
                        .WithMany()
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Harvest", b =>
                {
                    b.HasOne("Server.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.LandPlot", null)
                        .WithMany()
                        .HasForeignKey("LandPlotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.HarvestChemical", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.HarvestItem", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.TreeStock", null)
                        .WithMany()
                        .HasForeignKey("TreeStockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.HarvestProduct", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TreeProduct", null)
                        .WithMany()
                        .HasForeignKey("TreeProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.HarvestResult", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.TreeStock", null)
                        .WithMany()
                        .HasForeignKey("TreeStockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.HarvestSeed", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Seed", null)
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.HarvestTree", b =>
                {
                    b.HasOne("Server.Models.Harvest", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TreeStock", null)
                        .WithMany()
                        .HasForeignKey("TreeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.LandPlot", b =>
                {
                    b.HasOne("Server.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TreeStock", null)
                        .WithMany()
                        .HasForeignKey("TreeStockId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Server.Models.Livestock", b =>
                {
                    b.HasOne("Server.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.ProductionType", null)
                        .WithMany()
                        .HasForeignKey("MeatProductionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.ProductionType", null)
                        .WithMany()
                        .HasForeignKey("ProductionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Server.Models.LivestockDetail", b =>
                {
                    b.HasOne("Server.Models.Livestock", null)
                        .WithMany()
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("ParentOneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("ParentTwoId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Server.Models.LivestockMovement", b =>
                {
                    b.HasOne("Server.Models.Livestock", null)
                        .WithMany()
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.MedicalRecord", b =>
                {
                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.ProductionMovement", b =>
                {
                    b.HasOne("Server.Models.ProductionType", null)
                        .WithMany()
                        .HasForeignKey("ProductionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.SeedMovement", b =>
                {
                    b.HasOne("Server.Models.HarvestSeed", null)
                        .WithMany()
                        .HasForeignKey("HarvestSeedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.Seed", null)
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.StockFeed", b =>
                {
                    b.HasOne("Server.Models.Livestock", null)
                        .WithMany()
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.StockHistory", b =>
                {
                    b.HasOne("Server.Models.LivestockDetail", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.StockMovement", b =>
                {
                    b.HasOne("Server.Models.HarvestItem", null)
                        .WithMany()
                        .HasForeignKey("HarvestItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.HarvestResult", null)
                        .WithMany()
                        .HasForeignKey("HarvestResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.StockPhoto", b =>
                {
                    b.HasOne("Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.TreeProductMovement", b =>
                {
                    b.HasOne("Server.Models.HarvestProduct", null)
                        .WithMany()
                        .HasForeignKey("HarvestProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.TreeProduct", null)
                        .WithMany()
                        .HasForeignKey("TreeProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.TreeStock", b =>
                {
                    b.HasOne("Server.Models.LandPlot", null)
                        .WithMany()
                        .HasForeignKey("LandPlotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.TreeProduct", null)
                        .WithMany()
                        .HasForeignKey("TreeProductId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Server.Models.TreeStockMovement", b =>
                {
                    b.HasOne("Server.Models.HarvestItem", null)
                        .WithMany()
                        .HasForeignKey("HarvestItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.HarvestResult", null)
                        .WithMany()
                        .HasForeignKey("HarvestResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.TreeStock", null)
                        .WithMany()
                        .HasForeignKey("TreeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
