export const EN_GAPS = {
  farm: { fruitPeach: 'Peach', fruitPear: 'Pear', fruitCherry: 'Cherry' },
  harvest: {
    statusFlowering: 'Flowering',
    statusRipening: 'Ripening',
    statusEmergence: 'Emergence',
    statusHarvestReady: 'Ready to pick',
    statusTransferredToBalance: 'Moved to stock',
    stageDatesEdit: 'Edit dates',
    navOverview: 'Overview',
    navSeeds: 'Seed',
    navResult: 'Result',
    navChemicals: 'Chemicals',
    navMoney: 'Income',
    yieldSummary: 'Yield summary',
    gradeDistribution: 'Grade split',
    usable: 'Usable',
    wasted: 'Lost',
  },
  harvestResult: { onlyOne: 'A harvest has one result. Edit or remove the one it has.' },
  sales: { balanceUpdated: 'Stock updated' },
  harvestGrading: {
    title: 'Grading',
    harvested: 'Harvested: {amount} {unit}',
    graded: 'Graded: {amount} {unit}',
    colQuantity: 'Quantity',
    colWasted: 'Waste',
  },
  assessment: {
    colGrade: 'Grade',
    colSize: 'Size',
    colWeight: 'Weight',
    colMoisture: 'Moisture',
    colColor: 'Colour',
    upTo: 'up to',
  },
  treatment: {
    typeSpraying: 'Spraying',
    typePruning: 'Pruning',
    typeFertilization: 'Fertilising',
    typeIrrigation: 'Irrigation',
  },
};
