import { StyleSheet } from 'react-native';

import { Brand } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Brand.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: Brand.dark,
    textAlign: 'center',
  },
  headerSide: {
    minWidth: 24,
    alignItems: 'flex-start',
  },
  tabRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Brand.border,
  },
  tabItem: {
    marginRight: 28,
    paddingBottom: 12,
  },
  tabLabel: {
    fontSize: 15,
    color: Brand.muted,
  },
  tabLabelActive: {
    color: Brand.dark,
    fontWeight: '700',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: -1,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: Brand.dark,
  },
  tabBoxGrid: {
    paddingTop: 8,
    paddingBottom: 4,
    gap: 12,
  },
  tabBox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 16,
    padding: 14,
  },
  tabBoxIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: Brand.greenMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBoxIconImage: {
    width: 44,
    height: 44,
  },
  tabBoxLabel: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: Brand.dark,
    textAlign: 'left',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  stateBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  errorText: {
    fontSize: 13,
    color: '#C0392B',
  },
  retryButton: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  retryButtonLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Brand.dark,
  },
  cardInfo: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: Brand.dark,
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 13,
    color: Brand.muted,
  },
  livestockCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  livestockCardBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  livestockIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: Brand.greenMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  livestockIcon: {
    width: 38,
    height: 38,
  },
  stockIcon: {
    width: 48,
    height: 48,
  },
  detailCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  detailImage: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: Brand.greenMuted,
  },
  detailImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: Brand.greenMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailInfo: {
    flex: 1,
  },
  detailCode: {
    fontSize: 15,
    fontWeight: '600',
    color: Brand.dark,
  },
  detailAge: {
    fontSize: 13,
    color: Brand.muted,
    marginTop: 2,
  },
  detailActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  productCard: {
    width: '47%',
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 16,
    padding: 12,
    marginBottom: 14,
  },
  productImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: Brand.greenMuted,
  },
  productImageCentered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  productInfo: {
    marginTop: 10,
  },
  productMenuButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 13,
    color: Brand.muted,
  },
  feedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 20,
  },
  feedItem: {
    alignItems: 'center',
    width: 64,
  },
  feedIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: Brand.greenMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedAddIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Brand.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedAmountLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.dark,
    marginTop: 4,
    textAlign: 'center',
  },
  feedPickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  selectField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
  },
  selectFieldIcon: {
    width: 22,
    height: 22,
  },
  selectFieldText: {
    flex: 1,
    fontSize: 15,
    color: Brand.dark,
  },
  selectFieldPlaceholder: {
    color: Brand.muted,
  },
  selectOptionsList: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    marginBottom: 14,
    overflow: 'hidden',
  },
  selectOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Brand.border,
  },
  selectOptionActive: {
    backgroundColor: Brand.greenMuted,
  },
  selectOptionLabel: {
    flex: 1,
    fontSize: 15,
    color: Brand.dark,
  },
  landDetailsBlock: {
    gap: 4,
    marginBottom: 20,
  },
  historyHeroImage: {
    width: '100%',
    height: 200,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: Brand.greenMuted,
  },
  historyHeroPlaceholder: {
    width: '100%',
    height: 200,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: Brand.greenMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historySummary: {
    flexDirection: 'row',
    gap: 24,
    marginBottom: 16,
  },
  historyStatLabel: {
    fontSize: 12,
    color: Brand.muted,
    marginBottom: 2,
  },
  historyStatValue: {
    fontSize: 18,
    fontWeight: '700',
    color: Brand.dark,
  },
  historyList: {
    maxHeight: 240,
    marginBottom: 12,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 10,
  },
  historyRowUp: {
    backgroundColor: Brand.greenMuted,
  },
  historyRowDown: {
    backgroundColor: '#FBE3E0',
  },
  historyRowDate: {
    fontSize: 13,
    color: Brand.muted,
  },
  historyRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  historyRowWeight: {
    fontSize: 15,
    fontWeight: '600',
    color: Brand.dark,
  },
  historyRowWeightUp: {
    color: Brand.green,
  },
  historyRowWeightDown: {
    color: '#C0392B',
  },
  historyAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  historyAddInput: {
    flex: 1,
    marginBottom: 0,
  },
  historyAddButton: {
    backgroundColor: Brand.green,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyAddButtonLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  landCard: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    overflow: 'hidden',
  },
  landCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  landIllustration: {
    width: '100%',
    height: 140,
    borderRadius: 12,
    backgroundColor: Brand.greenMuted,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Brand.green,
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 4,
  },
  addButtonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Brand.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
  },
  sheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Brand.border,
  },
  sheetItemLabel: {
    fontSize: 15,
    color: Brand.dark,
    fontWeight: '500',
  },
  sheetItemDanger: {
    color: '#C0392B',
  },
  sheetCancel: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  sheetCancelLabel: {
    fontSize: 15,
    color: Brand.muted,
    fontWeight: '600',
  },
  formOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  formCard: {
    backgroundColor: Brand.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
  },
  formTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Brand.dark,
    marginBottom: 16,
  },
  formScrollArea: {
    maxHeight: 420,
  },
  formRow: {
    flexDirection: 'row',
    gap: 12,
  },
  formRowField: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Brand.dark,
    marginBottom: 6,
  },
  imagePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  imagePickerPreview: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: Brand.greenMuted,
  },
  imagePickerPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Brand.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePickerLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: Brand.dark,
  },
  input: {
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: Brand.dark,
    marginBottom: 14,
  },
  kindRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  kindChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  kindChipActive: {
    backgroundColor: Brand.green,
    borderColor: Brand.green,
  },
  kindChipIcon: {
    width: 18,
    height: 18,
  },
  kindChipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Brand.dark,
  },
  kindChipLabelActive: {
    color: '#FFFFFF',
  },
  kindChipAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Brand.border,
    borderStyle: 'dashed',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  kindAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexBasis: '100%',
  },
  kindAddInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 13,
    color: Brand.dark,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: Brand.muted,
  },
  statusBadgePlanting: {
    backgroundColor: Brand.greenMuted,
    borderColor: Brand.greenMuted,
  },
  statusBadgePlantingText: {
    color: Brand.green,
  },
  statusBadgeHarvested: {
    backgroundColor: Brand.green,
    borderColor: Brand.green,
  },
  statusBadgeHarvestedText: {
    color: '#FFFFFF',
  },
  formActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  formDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    marginTop: 12,
  },
  formDeleteLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#C0392B',
  },
  formCancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Brand.border,
    borderRadius: 14,
    paddingVertical: 14,
  },
  formCancelLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: Brand.dark,
  },
  formSubmitButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Brand.green,
    borderRadius: 14,
    paddingVertical: 14,
  },
  formSubmitButtonDisabled: {
    opacity: 0.5,
  },
  emptyHint: {
    fontSize: 13,
    color: Brand.muted,
    marginBottom: 14,
  },
  formSubmitLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  confirmCard: {
    width: '100%',
    backgroundColor: Brand.background,
    borderRadius: 18,
    padding: 20,
  },
  confirmTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Brand.dark,
    marginBottom: 6,
  },
  confirmBody: {
    fontSize: 13,
    color: Brand.muted,
    marginBottom: 18,
  },
  confirmDeleteButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C0392B',
    borderRadius: 14,
    paddingVertical: 14,
  },
});
